### ISSUE TITLE
question: dot product between numpy float32 and bit array

### ISSUE THREAD

**Issue by shaunc** [ilanschnell/bitarray#105]
I am doing a weighted combinatorial search, which involves generating very many (millions of) bit arrays using boolean operations on a initial set, then computing dot product of the resulting bit arrays with a numpy float32 vector. I also need to compute weighted hamming distances -- so same thing with xor.

Is this the right library to do this with? What is the best way to carry out the dot product? Just looping over the indexes doesn't seem right, unless I write it in Cython, which I may get to but don't want to start out with. Should I convert to bytes and then to a numpy array and let numpy do the dot product? (Also seems inefficient.) 

I'm grateful for suggestions -- whether using this library or something else.

**Comment by ilanschnell** [comment]
I don't think this library will help you directly.  In order to efficiently calculate the dot product, the bitarray will probably have to be converted to a numpy array with dtype bool (which will use one byte (instead of one bit) per element).  However, converting a bitarray to a numpy array with dtype bool is very efficent using bitarray's `.unpack()` method:
```
from bitarray import bitarray
import numpy as np

a = bitarray('10011')
b = np.frombuffer(a.unpack(), dtype=bool)  # array([ True, False, False,  True,  True])
c = np.arange(2, 7, dtype=np.float32)  # array([2., 3., 4., 5., 6.], dtype=float32)
d = b * c  # array([2., 0., 0., 5., 6.], dtype=float32)
```

**Comment by shaunc** [comment]
Ok -- thanks! In fact, thats what I've just done. Wrapped in Numba its running "well enough" for the moment. If you ever put in a "native" implementation of a dot produce (or something that generalizes it), though, I'd be happy to use it!

Thanks for the library.

**Comment by ilanschnell** [comment]
Ah, yes.  You want the inner product.  If your bitarrays are sparse, you could also try:
```
sum(c[i] for i in a.itersearch(bitarray('1'))
```
That is, you only sum up the elements of `c` whose index `i` is true in the bitarray `a`.  But I guess this will almost always be much slower.
