### ISSUE TITLE
Bitwise operation ~ doesn't work on '1' (1 doesn't flip to 0, works the other way though)

### ISSUE THREAD

**Issue by bajpaijalaj** [ilanschnell/bitarray#107]
from bitarray import bitarray
test = bitarray('1')
print(test)
test[0] = ~ test[0]
print(test)

![image](https://user-images.githubusercontent.com/38458301/99320081-17bff580-286b-11eb-8655-7039143fb820.png)

**Comment by ilanschnell** [comment]
Thank you for using bitarray!  The problem in our example is that `~` operates on `test[0]` (which is `True`).  So `~ True` (which is the same as `~ 1` evaluates to `-2`.  And the truth value of `-2` is True.

Bitarrays support the `~` operator:
```
test = ~test
```
This will invert the *entire* bitarray.  You can achieve the same using the in-place operation:
```
test.invert()
```

If you want to flip a *single* element use:
```
test[i] = not test[i]
```
as of version 1.5.3, you can also do:
```
test.invert(i)
```

```
