### ISSUE TITLE
Cannot inherit from bitarray

### ISSUE THREAD

**Issue by fstop22** [ilanschnell/bitarray#108]
I am trying to create a derived class using _bitarray_ as the parent.  However, I keep getting following error:

```
Python 3.8.3 (default, Jul  2 2020, 16:21:59)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitarray import bitarray
>>> class derived(bitarray):
...     def __init__(self, *args, **kwargs):
...         super().__init__(*args, **kwargs)
...
>>> a = derived('1011')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __init__
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

Thanks,
Jeff

**Comment by fstop22** [comment]
However, it seems to work fine in Python 2.
```
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitarray import bitarray
>>> class derived(bitarray):
...     def __init__(self, *args, **kwargs):
...         super(derived, self).__init__(*args, **kwargs)
...
>>> a = derived('1011')

```

**Comment by ilanschnell** [comment]
Thank you for using bitarray!  It is possible to derive from `bitarray` (there is even a test for this https://github.com/ilanschnell/bitarray/blob/master/bitarray/test_bitarray.py#L725, which passes for all supported Python versions).  The problem your running into appears to be due to `super()` (which I'm not very familiar with).

**Comment by ilanschnell** [comment]
In fact, the `frozenbitarray` class (which is part of this package and well tested) is also derived from `bitarray`.
