### ISSUE TITLE
Unexpected result from bitarray.tobyte()

### ISSUE THREAD

**Issue by amjadtaleb** [ilanschnell/bitarray#111]
I am getting a wrong buffer from tobyte method, examples:

```
#  the string is shown in 4bits for human visibility, it does not affect the result no matter how I insert the value of x
>>> x_str = '0001 1110 1000 0001 0000 0100'.replace(' ', '')
>>> x = bitarray(x_str)
>>> x.tobytes()

b'\x1e\x81\x04'

>>> a = bitarray(x_str, endian='big')
>>> a.tobytes()
b'\x1e\x81\x04'

```
I was expecting the buffer result to `b'\x1e\x81\x00\x04'`.

hardware: Fedora 5.9.16-100.fc32.x86_64 on Intel(R) Core(TM) i7-7700K CPU with Python 3.8.6

EDIT: After many trials I found that the problem is in the way python represents byte order, some people use `struct` module to resolve to problem, and others use byte masking like [this one](https://stackoverflow.com/questions/5995812/python-decimal-to-hex-reverse-byte-order-hex-to-decimal)

**Comment by ilanschnell** [comment]
Yes this is what I would expect.  Why did you expect `b'\x1e\x81\x00\x04'` (with the extra zero byte)?

**Comment by amjadtaleb** [comment]
You are right, the problem turned out to be caused by the way python represents byte order for 16 and 32 bit numbers, and not in bitarray. My example was wrong anyway I got confused after many hours counting bits and trying to find where the problem in code was coming from. 

The actual problem was that I need to create a buffer from various numbers of various lengths, 8, 16 and 32 bits. I was feeding these numbers to bitarray using formatted strings, however python reversed the byte order and the buffer was getting missed up.
Feel free to delete this issue if possible, otherwise just close it. Apologies for the confusion.

**Comment by ilanschnell** [comment]
No problem.  Thank you for using bitarray!
