### ISSUE TITLE
Segmentation fault using bitarray

### ISSUE THREAD

**Issue by srobertjames** [ilanschnell/bitarray#12]
Hi.  I just installed bitarray and have found a segfault.  I'm able to reduce it down to this code:

In [1]: from bitarray import *
In [2]: b = bitarray([False, True, False, False, True])
In [3]: t = bitarray([True])
In [4]: b.itersearch(t)
zsh: segmentation fault  ipython

Using:
Python 2.7.2+ (default, Jul 20 2012, 22:15:08) 
[GCC 4.6.1] on linux2
Installed bitarray using easy_install

**Comment by ilanschnell** [comment]
Sorry for the late response.  I cannot reproduce this issue.  Also, there are tests which over `itersearch`, so I'm not sure what's going on in your setup.
