### ISSUE TITLE
Feature request: Non zero index positions

### ISSUE THREAD

**Issue by sanjaysrikakulam** [ilanschnell/bitarray#125]
Hi @ilanschnell 

Is it possible to have a feature that will return the non-zero index positions from the given bitarray?

For example like in NumPy:
```
import numpy as np
np.nonzero(np.empty(10000000000, dtype=bool)) #This will return the non zero index positions
```

One can use NumPy for getting the non-zero index positions of a bitarray as well but with the biggest downside of wasting too much of the memory because we will have to convert the bits to boolean (so 1:8 wastage)
```
from bitarray import bitarray
import numpy as np
x = bitarray(10000000000)
x.setall(0)
np.nonzero(np.frombuffer(x.unpack(), dtype=bool))
```

It will be a really good nice to have feature. If possible please consider. 

Thank you!

**Comment by ilanschnell** [comment]
Hello!  This functionality already exists, you can use the `.search()` method.
```
from bitarray import bitarray

a = bitarray(100)
a.setall(0)
a[31] = a[52] = a[79] = 1
print(a.search(bitarray('1')))
```

**Comment by sanjaysrikakulam** [comment]
Hi @ilanschnell 

Oh, that's great, did not realize that usage for search! Thank you! :-)

**Comment by ilanschnell** [comment]
As of version 2.1.0, you can also search for a Boolean item: `a.search(1)`

**Comment by sanjaysrikakulam** [comment]
Thank you for adding that feature! :-)
