### ISSUE TITLE
Slicing Performance

### ISSUE THREAD

**Issue by danielg1111** [ilanschnell/bitarray#132]
It appears that `setslice_bool` is considerably slower than it could be for cases when the slice's step isn't 1.  Setting a portion of the bits can be nearly 100x slower than setting all of them, as shown below.

```python
bits = bitarray(10 ** 9)
%timeit bits[:] = True
6 ms ± 184 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit bits[::2] = True
564 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

While it's not surprising that setting every bit is faster, since that's essentially just a call to `memset`, it seems like the performance difference is larger than necessary.

In `setslice_bool`, it calls `setbit` in a loop, which does bounds checking and other work in every iteration.  Perhaps performance could be significantly improved by moving some of the work outside the loop?

**Comment by ilanschnell** [comment]
Thank you for using bitarray and the feedback!  Yes, `memset()` is considerably faster.  The bound checking in `setbit()` is only done in debug mode, ie. when you normally compile Python C extensions the ` -DNDEBUG` flag is used.  I don't think it is possible to speedup the `step != 1` case much further.  There is a lot more computation that needs to be done in this case, as existing bits cannot be simply overwritten.

Last year, I realized that `richcompare()` could be improved by using `memcmp()` in special cases.  I saw similar speedups (100x) for those cases also.  See changelog for version 1.4.1.

**Comment by danielg1111** [comment]
Ah.  I didn't realize the bounds checking was only in debug mode.  If I were to find a way to speed it up significantly, would it be worth making a pull request?  (mostly asking since `contributing.md` says that pull requests will most likely be rejected)

**Comment by ilanschnell** [comment]
I want to keep the implementation simple (not having too many special cases), while also having it fast.  So it depends...
Suggestions on how to make this faster are certainly welcome, although (as mentioned earlier) I don't see a way to speed the `step != 1` case much further.

Do you have a specific idea on how to make this faster?

**Comment by danielg1111** [comment]
It might be faster if you computed the bitmasks ahead of time. You'll never need more than 8 different ones since they'll repeat cyclically due to how modular arithmetic works.  Computing all the bitmasks ahead of time could mean less work in each iteration.

This would also enable a large speedup for when `step` is small: you could use the same bitmask to set up to 4 bits at once (or up to 32 if you cast to `long long`).  I guess setting more than 1 bit at once might require a special case, but I think the speedup would be very large.

**Comment by ilanschnell** [comment]
I have an idea!  To make this faster, one could (here for `a[::2] = 1`) basically try something like:
```
a = bitarray(10 ** 9)
b = (len(a) // 8) * bitarray('01010101').    # works only because len(a) % 8 == 0
a |= b
```
That is, one creates a bitarray `b` which can then be applied to `a` using a bitwise operation.  However, there will be many special cases.  Moreover, this method is very memory intensive.

Are you only interested in the `step = 2` case?  What is your objection?

**Comment by ilanschnell** [comment]
Funny, we has basically the same idea at the same time!  I didn't see your response until after I made my comment.
I tried to time my test code above and `(len(a) // 8) * bitarray('01010101')` is very costly (as costly as `a[::2]` actually).
However, then I tried:
```
%timeit b = (1000 * bitarray('01010101')) * 125_000
25.2 ms ± 50.5 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit a | b
110 ms ± 396 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
So we have about 135ms (on my system), compared to 1.1s.  So this almost 10 times faster.
```
%timeit a[::2] = 1
1.1 s ± 3.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by ilanschnell** [comment]
Since setting slices is a limited use case, and also because of the increased complexity and memory usage, I would suggest perhaps making a new utility function `bitarray.util.setslice()`:
```
setslice(a, slice, value)
# equivalent to
a[slice] = value

# For example:
s = slice(7, -30, 2)
setslice(a, s, True)
# does the same as
a[s] = True
```
This function would be faster for `step = 2 .. 30?` if `stop - start` is large (maybe 1000).  `setslice()` could be implemented in C and use some empirical heuristics for determining when it would fallback to `.__setitem__()`.

I don't have the time and energy to work on this now, but you (@danielg1111 ) might feel eager enough!

**Comment by danielg1111** [comment]
While I was tinkering with this, I noticed that `bitwise()` can be sped up by around 3x by casting the pointers to `long long` and reducing the number of iterations by a factor of 8.  Would that be worth changing?

**Comment by ilanschnell** [comment]
Yes, `bitwise()` could be sped up (and maybe a few other things as will).  I while ago I was thinking about moving to an internal bitarray representation where the buffer member (`.ob_item` in `bitarrayobject`) could be of type `uint64_t *` (instead of `char *`).  This could speed up several things, but also make things like `.frombytes()`, etc. more complicated.  So I'd rather not change the `bitarrayobject` struct.

But yes, casting in `bitwise()` could be worth it, in particular since this is much easier (no start, step).

**Comment by ilanschnell** [comment]
I just created #133 to following your suggestion.  The speedup I'm seeing from this (on 10^9 bitarrays) is about 2.35

**Comment by danielg1111** [comment]
The PR looks good to me.  I guess the speedup is larger on my machine.

**Comment by danielg1111** [comment]
I thought of a simpler way to speed up slice assignment that can help in a wider range of cases and doesn't need a bunch of extra memory.  There are a couple ways to take work out of the main loop.

Computing the bitmaps can be done beforehand by using a tiny array as a lookup table for the 8 possible bitmaps.  Choosing `&=` or `|=`  can also be taken out of the main loop, like in `bitwise()`.  These changes almost double the speed for `step <= 50` (at least on my machine).  

Since this optimization is simpler and doesn't require extra memory, would it make sense to put it in `setslice_bool()`, or would it still go in a new function `bitarray.util.setslice()`? (or neither if you don't think it's a good idea)

**Comment by ilanschnell** [comment]
Interesting.  I'm not exactly sure what your approach to speedup is here.  Could it maybe be applied to `setbit()` in general?  If the changes almost double the speed and don't introduce too much complexity it is worth considering having them in `setslice_bool()` itself.  Can you create a PR such that I can better understand what the idea is, and also do some testing on my various machines?  It doesn't have to be perfect.  Thanks

**Comment by danielg1111** [comment]
I just made the PR.  Storing the bitmasks in a tiny table could likely be applied to `setbit()`, although it would be slightly trickier, since it might need to have a 2D array of masks to account for both little-endian and big-endian.  There's also some chance working with a 2D array could be slower and defeat the point.  The only way I can think of to avoid needing it to be 2D would be adding the lookup table as part of the `bitarray` struct.

I don't think the other optimization could be directly applied to `setbit()` directly, but it might be possible to achieve a similar speedup in some cases by adding functions like `setbit_to_1()` and a `setbit_to_0()`.

**Comment by ilanschnell** [comment]
I'm also seeing the (even though small) speedup from switching from `/ 8` to `>> 3` and from `% 8` to `& 7`.  I'm a bit surprised about this because I thought that modern compilers (here clang 11.1) are already doing optimizations like this one.

I would rather not change the `bitarrayobject` struct.  Having a 2D array shouldn't be expensive (although creating the bitmask isn't expensive to being with).  A while back I realized that `setunused()` (in `bitarray.h`) can be optimized from looping over `setbit()` to using a special mask, so this is using a 2D bitmask table already.

`setslice_bool()` was certainly low hanging fruit for this type of optimization!

**Comment by ilanschnell** [comment]
In a8c4ab66023f3cdf7471d981dd8bea77dfaf6b28, I just changed to use bitwise operations in getbit() and setbit().  For the operation `del a[0]` on a bitarray with 10^9 elements, I'm seeing a speedup from 3.35s to 2.32s!  This operation calls `getbit()` and `setbit()` on all billion elements (whereas `del a[:8]` calls `memmove()` and only takes 0.12s).

**Comment by danielg1111** [comment]
> I'm also seeing the (even though small) speedup from switching from `/ 8` to `>> 3` and from `% 8` to `& 7`. I'm a bit surprised about this because I thought that modern compilers (here clang 11.1) are already doing optimizations like this one.

I was also surprised the compiler wasn't already doing this.  Perhaps it only bothers if you compile with `-O3`? (or whatever the Windows equivalent is)

**Comment by ilanschnell** [comment]
I just checked: it was using `-O2` when I tried it yesterday, but with `-O3` it's the same speedup (`clang version 11.1.0`).  Maybe other compilers know how to handle this.

**Comment by ilanschnell** [comment]
I think with #135 being merged we can close this issue.  Just for the record, I tried to improve the performance further by crating a mask array which is then applied repeatedly.  For small step sizes (2..7) fewer `|=` and `&=` operations then needed.  However, it wasn't really faster, but a lot more complicated.  Here is the relevant code (in `setslice_bool()`):
```
        else if (step <= 8 && stop - start > 100) {
            const Py_ssize_t byte_start = BYTES(start);
            const Py_ssize_t byte_stop = stop >> 3;
            Py_ssize_t j, k;
            char mask[8];

            for (i = start; i < BITS(byte_start); i += step)
                setbit(self, i, vi);

            assert(i / 8 == byte_start);
            for (k = 0; k < 8; k++)
                mask[k] = 0;

            for (;i < BITS(byte_start + 8); i += step) {
                j = i - BITS(byte_start);
                assert(j / 8 < 8);
                mask[j >> 3] |= BITMASK(self->endian, j);
            }

            k = 0;
            while (mask[++k] != mask[0]);
            assert(k < 8 && k % 2);

            if (vi) {
                for (j = byte_start; j < byte_stop; j++)
                    self->ob_item[j] |= mask[(j - byte_start) % k];
            }
            else {
                for (j = byte_start; j < byte_stop; j++)
                    self->ob_item[j] &= ~mask[(j - byte_start) % k];
            }
            for (i = BITS(byte_stop); i < stop; i++)
                if ((i - start) % step == 0)
                    setbit(self, i, vi);
        }
```
