### ISSUE TITLE
Random bitarray with probability of a bit being set is p.

### ISSUE THREAD

**Issue by tapadeep** [ilanschnell/bitarray#134]
I'm very new to bitarray. I require a utility function where I would like to output a bit array of size n where the probability of each bit being 1 is p. How can I do this the most efficient way? 

Thanks in advance.

**Comment by ilanschnell** [comment]
Most straight forward implementation:
```
from random import random
from bitarray import bitarray

def random_p(n, p):
    return bitarray(random() < p for _ in range(n))
```
I'm not sure how to make this function faster.  For the special case `p = 0.5` the utility function `bitarray.util.urandom()` is obviously much faster.
