### ISSUE TITLE
cant install bitarray

### ISSUE THREAD

**Issue by Plorred-hash** [ilanschnell/bitarray#152]
(https://user-images.githubusercontent.com/54238814/141684166-5ca10f26-ca3f-4c97-a566-5a89bb0a6225.png)

**Comment by Plorred-hash** [comment]
i installed a package including 2015,2017,2019,2022 still wont install, same error

**Comment by ilanschnell** [comment]
I've just release bitarray 2.4.0 which now has binary wheel packages for all major platform an PyPI as well.  So `pip install bitarray` should work without the need to having MSVC installed.
