### ISSUE TITLE
Feature Request: Add value parameter to count_* functions

### ISSUE THREAD

**Issue by alancleary** [ilanschnell/bitarray#154]
The `count` method of the `bitarray` object has a `value` parameter that allows users to specify whether they want to count `1`s or `0`s. The `count_*` functions, however, do not have such a parameter, limiting users to counting only `1`s. Can a `value` parameter be added to the `count_*` functions to allow counting `0`s as well?

For example, if this feature were added to the `count_n` function, then its documentation would be:

`count_n(a, n, value=1, /)` -> int
    Return lowest index `i` for which `a[:i].count(value) == n`. Raises `ValueError`, when `n` exceeds total count (`a.count(value)`).

**Comment by ilanschnell** [comment]
Thanks for this suggestion.  I've added the additional value parameter to `count_n()` as you suggested in PR #161.  This will be merged soon, and part of the next release.

However, adding the additional value parameter to `count_and()`, `count_or()` and `count(xor)` seems confusing to me.  Also those counts can be easily obtained by subtracting the count from the length, e.g.:
```
count_and(a, b, value=0) = len(a) - count_and(a, b)
```

**Comment by ilanschnell** [comment]
The additional value parameter was added to `count_n()` in the 2.3.6 release.

**Comment by alancleary** [comment]
Thanks @ilanschnell! This is going to be very handy.
