### ISSUE TITLE
interacting with numpy

### ISSUE THREAD

**Issue by christian2022** [ilanschnell/bitarray#155]
Is there an example for how "Packing and unpacking to other binary data formats, e.g. numpy.ndarray." works?
Especially if you have want to have an array of bitarray...

**Comment by ilanschnell** [comment]
Thanks for using bitarray!  Yes, there is such an example:
https://github.com/ilanschnell/bitarray/blob/master/examples/ndarray.py

**Comment by christian2022** [comment]
Sorry haven't seen the examples subfolder. Any idea on how to use an `ndarray` of `bitarray` and still benefitting from the packed format of `bitarray`?
