### ISSUE TITLE
what's wrong with it?

### ISSUE THREAD

**Issue by dreambe** [ilanschnell/bitarray#157]
from bitarray import bitarray

x1 = bitarray(10)
m = [1, 3, 8]

for i in m:
    x1[i-1] = 1

for i in range(0, len(x1)):
    if x1[i] == 1:
        print(i+1)

if you run tiwice the code, you will find the result are diffrent...

![飞书20211213-151800](https://user-images.githubusercontent.com/3831001/145768769-6ec08596-1505-4695-a338-b2777a9282c8.png)

**Comment by ilanschnell** [comment]
The problem is that when you create a bitarray of given length (`bitarray(10)`), the elements are uninitialized.  You can use the `.setall()` method to set all elements to either 0 or 1:
```
x1 = bitarray(10)
x1.setall(0)
```
Or you can use the `zeros()` utility function:
```
from bitarray.util import zeros
x1 = zeros(10)
```
