### ISSUE TITLE
Test Failures in s390x

### ISSUE THREAD

**Issue by varlackc** [ilanschnell/bitarray#159]
Issue:
`bitarray` test fails for `linux-s390x` due to a big/little-endian issue

Details:

There seems to be an issue during the test on bitarray for linux-s390x
The issue seems to be a big/little-endian issue in the testsuite of bitarray

Here is the error:
FAILED (failures=24, errors=1)

Traceback (most recent call last):

File "/opt/conda/conda-bld/bitarray_1639775601698/test_tmp/run_test.py", line 7, in

assert bitarray.test().wasSuccessful()
AssertionError

Tests failed for bitarray-2.3.4-py37h2a837d6_1.tar.bz2 - moving package to /opt/conda/conda-bld/broken

**Comment by ilanschnell** [comment]
Thank you for reporting this issue.  I am very interested in finding the root cause of this issue.  Can you change the recipe to run
```
assert bitarray.test(verbosity=2).wasSuccessful()
```
and post the output?  This will give me a much better hint where the problem is.  Thanks

**Comment by ilanschnell** [comment]
Looking into this some more, I think the problem is in `shift_r8()`, when undefing  ` PY_UINT64_T` things work fine on s390x.

**Comment by ilanschnell** [comment]
#160 fixes this issue, and will be part of the 2.3.5 release
