### ISSUE TITLE
ModuleNotFoundError: No module named 'bitarray._bitarray'

### ISSUE THREAD

**Issue by Rogerspy** [ilanschnell/bitarray#169]
```python
In [1]:  from bitarray import bitarray
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-de5cf3449d64> in <module>
----> 1 from bitarray import bitarray

~/anaconda3/lib/python3.7/site-packages/bitarray/__init__.py in <module>
      9 Author: Ilan Schnell
     10 """
---> 11 from bitarray._bitarray import _bitarray, bitdiff, bits2bytes, _sysinfo
     12 
     13 __version__ = '0.8.3'

ModuleNotFoundError: No module named 'bitarray._bitarray'
```

**Comment by ilanschnell** [comment]
Thanks you reporting this issue.  How did you install bitarray?  I see you are using Anaconda, so bitarray should be installed.  The strange thing is that even though `bitarray/__init__.py` is present, the C extension `bitarray/_bitarray.so` does not seem to be installed.  Also, the version of bitarray appears to be 0.8.3, which is about 2.5 years old.  The latest version is 2.3.7.  Have you tried `conda update bitarray`?

**Comment by Rogerspy** [comment]
> 

```
conda update bitarray
```

it works for me, thank you.

**Comment by godwincharan** [comment]
I am using python 
Python 3.12.1
And I have bitarray
Requirement already satisfied: bitarray in c:\python312\lib\site-packages (2.9.2)

I get still same errors 
   File "C:\Python312\Lib\site-packages\bitarray\__init__.py", line 14, in <module>
     from bitarray._bitarray import (bitarray, decodetree, _sysinfo,
 ModuleNotFoundError: No module named 'bitarray._bitarray
