### ISSUE TITLE
huffman code error for single key dict

### ISSUE THREAD

**Issue by eyaler** [ilanschnell/bitarray#172]
This is an edge case, where huffman_code() fails if the dict has only a single key:

`huffman_code(Counter('xxx'))`

> Out[1]: {'x': bitarray()}

This is not useful and will of course cause encode() to fail:

`bitarray().encode(huffman_code(Counter('xxx')), 'xxx')`

> ValueError: non-empty bitarray expected

**Comment by eyaler** [comment]
This is my fix, where also I find it useful to gracefully deal with the empty case:
```
        if len(counter) > 1:
            table = huffman_code(counter)
        elif len(counter) == 1:
            table = {list(counter)[0]: bitarray(1)}
        else:
            table = {}
```

**Comment by eyaler** [comment]
@ilanschnell thanks for your detailed response and commit! (and bitarray of course)

as regard to the edge cases:

i am not aware of the practice of encoding the length with huffman. anyway this is not a requirement of huffman, and moreover streaming decoders do exist, so sometimes the length is not defined. specifically i implemented one of the stream decoders from here: https://www.researchgate.net/publication/3159499_On_the_implementation_of_minimum_redundancy_prefix_codes

although encoding the length for a single symbol makes sense from a compression perspective, this takes us to the domain of [modified Huffman ](https://en.wikipedia.org/wiki/Modified_Huffman_coding) which makes use of run-length encoding, which sounds like what you described. also as you've mentioned, you still need to save the cleartext symbol in the table.

anyway, i was stress testing some edge cases where huffman encoding/decoding is part of the process and i did want the flow to go through also for these degenerate cases. so this was more of a pragmatic remark rather than a purist or philosophical one. while failing on empty strings seems like a reasonable design decision, i would at least except the single symbol case to work.

as regard to `bitarray(1)` i was indeed aiming for `bitarray('1')`. as this may be a common cause for bugs, i would suggest to require a keyword like length/shape/size, e.g. `bitarray(length=1)`, or you could even make the keyword necessary just for the cases 0, 1 (assuming only binary codes are supported). otherwise, since this is not seem like a familiar idiom for python array constructors, i find the current behavior lacking in terms of least surprise and discoverability.

**Comment by ilanschnell** [comment]
Thanks for your detailed response.  I agree that the having an empty bitarray as a result is surprising, and most likely not what one would expect or want.  I'm thinking about returning `{list(counter)[0]: bitarray('0')}` for this case.

In regards to `bitarray(1)`, this is the same behavior of Python's built-in `bytearray`:
```
>>> bytearray(1)
bytearray(b'\x00')
```
I have though about the cases `bitarray(True)` and `bitarray(False)` for which you get `TypeError: cannot create bitarray from bool`.  Requiring a `length` keyword would break existing code.

BTW: I've been working on canonical Huffman coding for the last few days, see #173.  This is be part of the upcoming bitarray 2.5.0 release.
