### ISSUE TITLE
Feature: bit-packing for ints; move data between ints and bytearray slices

### ISSUE THREAD

**Issue by yonillasky** [ilanschnell/bitarray#182]
The functionality can be described as:
`b.from_int(x, y, a)`, where `a` is an int in the range `0 <= a < 2 ** (y - x)`. overwrites b[x:y].
`a = b.to_int(x, y)`, returns the conversion of b[x:y] to an int in the range `0 <= a < 2 ** (y - x)`

there could be an endianness flag, which determines whether bit `x` or `y-1` is the MSB.
we could also offer an `append_int` operation, which would take `a` and `length` (in bits).

I found no way to implement such operations with existing features unless I make many complex transformations to the data (which would probably copy the underlying binary data at least three times, instead of just once).

I'm willing to implement this.
I just want to make sure it isn't already available in some way that I've missed.

**Comment by ilanschnell** [comment]
Thanks for using bitarray and suggesting this feature.  Have you looked at the utility functions `bitarray.util.int2ba()` and `bitarray.util.ba2int()`?  Using these functions you can say:
```
b[x:y] = int2ba(a, y-x)
```
and
```
a = ba2int(b[x:y])
```
I would argue that this is straightforward enough.  Do you have a special use case?

**Comment by yonillasky** [comment]
Thanks. I missed those functions somehow. It does what I want, except only for the bit order control (which at worst, I could write a separate function for - to reverse the bits of an int). So I am closing this issue. Thanks.

**Comment by ilanschnell** [comment]
Noe that the function `int2ba()` has an optional `endian` argument, and `ba2int()` uses the endianness of the bitarray given.
