### ISSUE TITLE
Bit-packing can be more efficient

### ISSUE THREAD

**Issue by timhuff** [ilanschnell/bitarray#183]
Every byte has the following schema:
bit 1: does next byte follow
yes? 
- bits 2 to 8: data
no? 
- 8: does the data in this byte need to be bit-flipped?
- bits 2 to 7: potentially bit-flipped data

This means that there can only be 6 data bits in the last byte. If there's 7 bits in the end, you just write `1111 1111 \ 0000 0000`

**Comment by ilanschnell** [comment]
Thanks for your interest in bitarray and opening this issue.  However, I'm missing the context.  Are you suggesting an improvement to `util.vl_encode()` and `util.vl_decode()`?
