### ISSUE TITLE
Feature: using slicing/indexing following the endianness

### ISSUE THREAD

**Issue by TheFausap** [ilanschnell/bitarray#184]
Hello,

is it possible to make the slicing and indexing aware of the endianness? 

I mean:

`A = bitarray('01000001')` as big-endian,

A[7] = 0, A[6] = 1, ... A[0] = 1

and, of course, the opposite for little-endian.

thanks,
Fausto

**Comment by ilanschnell** [comment]
Hello Fausto, the bit endianness of a bit array does not change how it is indexed, only how it is represented on the machine level.  In your example, it would not matter if the array `A` is little or big-endian for how you index elements:
```
>>> A = bitarray('01000001', 'big')
>>> A[7]
1
>>> A.tobytes()
b'A'
>>> A = bitarray('01000001', 'little')
>>> A[7]
1
>>> A.tobytes()
b'\x82'
```
That is, the last element in `A` is always 1 (regardless of endianness).  However, the underlying byte representation will be different.

**Comment by ilanschnell** [comment]
So to answer your original question: Although it would probably be possible to make the indexing endianness aware, this is not what the endianness is about and it would be confusing to add such a feature.  You may want to look at the `.reverse()` and `.bytereverse()` methods to solve your problem at hand, or simply write a function that does the reindexing for you.  I'm closing this issue now, but please feel free to comment.  I would be interested to understand what problem you are trying to solve.

**Comment by TheFausap** [comment]
Thanks for the info. Yes you are right it could be pretty confusing, but working with non-standard size for the array could be helpful. I was speaking about endianness because it impacts the MSB and LSB in a sequence of bits.
If I am working with 36 bits words, it could be helpful (from the programmer's point of view) if I could decide based on the endianness if A[35] is my MSB or LSB. But I solved writing a custom function. :)
