### ISSUE TITLE
Feature: divide

### ISSUE THREAD

**Issue by arsserpentarium** [ilanschnell/bitarray#191]
I suggest to add divide function, which purpose is to divide bitarray into list of smaller bitarrays of specified length:
`
 >>>divide(bitarray('001001001001001001', 3)
[bitarray('001'), bitarray('001'), bitarray('001'), bitarray('001'), bitarray('001'), bitarray('001')]

even better if there would be optional param to specify, if you want to get list  of integers or bitstrings instead of bitarrays.

sorry for pester with feature requests. Your lib is very useful. And it might become even more powerful tool. thank you again.

**Comment by ilanschnell** [comment]
Thank you for your feature request!  The function you want is rather simple:
```
def divide(a, n):
    return [a[i:i + n] for i in range(0, len(a), n)]
```
I'm hesitant to add simple functions to bitarray, unless there is a clear benefit.

Also, if you only want a nicer representation of a bitarray, the functionality is already there:
```
>>> from bitarray import bitarray
>>> from bitarray.util import pprint
>>> a = bitarray('001001001001001001')
>>> pprint(a, group=3)
bitarray('001 001 001 001 001 001')
```

**Comment by arsserpentarium** [comment]
I asked for that function precisely, because it's implementation is horribly slow in python.
