### ISSUE TITLE
Type of single digit slice

### ISSUE THREAD

**Issue by kitterma** [ilanschnell/bitarray#192]
I'm not sure if this is intentional or not.  I could not find it in the documentation.

```
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitarray
>>> x = bitarray.bitarray('01010101')
>>> print(type(x[2:4]))
<class 'bitarray.bitarray'>
>>> print(type(x[4]))
<class 'int'>
```

Is the single digit slice supposed to be an integer?  If so, is it in the documentation?

**Comment by ilanschnell** [comment]
Thank you for your using bitarray!  Yes, this is the intended behavior:  The `.__getitem__()` method will return the element of the bitarray as an integer.  I'm not sure if this behavior is explicitly mentioned in the documentation.  However, the return type of `.__getitem__()` is part of the Python type interface: https://github.com/ilanschnell/bitarray/blob/master/bitarray/__init__.pyi#L87

**Comment by kitterma** [comment]
Wild.  I had no idea.  Thanks.  I think that covers it.
