### ISSUE TITLE
 module 'bitarray' has no attribute 'util'

### ISSUE THREAD

**Issue by Tenglon** [ilanschnell/bitarray#193]
Hi, After install the library with 

conda install bitarray -c conda-forge, I have confirmed to install a 2.7.3 version, but the util module is missing in this library.

The outputs are:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/62259673/236668742-6d30f240-b0f7-4f20-a8d7-791d12662493.png">

**Comment by ilanschnell** [comment]
`bitarray.util` is it's own module, not an attribute of the `bitarray` module.  In order to use it's functionality, it needs to imported:
```
import bitarray.util
```
For example:
```
>>> from bitarray.util import int2ba
>>> int2ba(789)
bitarray('1100010101')
```
