### ISSUE TITLE
Problem creating bitarrays that share the same buffer

### ISSUE THREAD

**Issue by scott-griffiths** [ilanschnell/bitarray#194]
Hi. I'm not sure if this is intended behaviour or not but I'm interested in how and when different bitarrays can share the same buffer in memory.

The example that is confusing me is when I create one bitarray from the buffer of another the memory appears to be shared but the length changes: 

```
>>> x1 = bitarray('11')
>>> x2 = bitarray(buffer=x1)
>>> x1
bitarray('11')
>>> x2
bitarray('11000000')
>>> x1.buffer_info()
(4518774448, 1, 'big', 6, 4, 0, 0, 1)
>>> x2.buffer_info()
(4518774448, 1, 'big', 0, 0, 0, 1, 0)
```

I'm presuming that this is because the `padbits` of the copy gets reset to zero. I'm not sure if this is a bug, or how to work around it (while keeping the memory address of the buffers of both bitarrays the same).

I've also tried using `frozenbitarray` objects, hoping that `frozen2 = frozenbitarray(frozen1)` would make them share a buffer, but it appears to just copy.

Great work on this module by the way - I've been testing it to destruction recently and it's held up really well. I'm looking at using it to replace the guts of the bitstring module - some details here if you're interested: https://github.com/scott-griffiths/bitstring/discussions/260

**Comment by ilanschnell** [comment]
Thank you for your interest in bitarray!  Buffers are always byte arrays.  That means they are represented by a pointer to a memory start location and their size in bytes (not bits).  Hence, when importing a buffer from another object (even another bitarray), you are importing a contiguous memory segment.  This memory segment has no information about what it actually represents.   Therefore, the bit-endianness as well as the number of padbits are lost when using `bitarray(buffer=x1)`, and the result will always be a bitarray with a multiple of 8 bits.  So what you describe in your example is not a bug.

A `frozenbitarray` can only be created from a readonly buffer:
```
>>> a = bitarray('10011')
>>> b = frozenbitarray(buffer=a)
...
TypeError: cannot import writable buffer into frozenbitarray
```
This prevents the frozen object to be mutated by changing its buffer.

I hope this helps.  I'm not exactly sure what your goal is.  Can you explain why you want to a create bitarray which shares the buffer of another bitarray?

**Comment by ilanschnell** [comment]
BTW: this piece of documentation might also help:
https://github.com/ilanschnell/bitarray/blob/master/doc/buffer.rst

**Comment by scott-griffiths** [comment]
Thanks for the information - I think I understand it better now. The use case is really just so I can be flexible and efficient in not copying data when creating one bitarray from another if I know that it can be treated as immutable.

So if I have one large bitarray that I know is immutable (e.g. it was created from a buffer that's a `bytes` object or a read-only `mmap`) I'd like to take an arbitrary (continuous) slice as another bitarray without it copying memory or reading the file.

```
>>> a = bitarray(buffer=bytes(1000))  # Could also be from a read-only mmap for example
>>> b = a[x:y]
```
So I'm trying to find a way to create `b` for arbitrary values of `x` and `y` as an O(1) operation. It's easy enough if `x` and `y` are both multiples of 8.

My workaround I think would be to write a wrapper class that reimplements things like `__getitem__` and `__len__` to account for an offset of 0->7 bits and a different length.

Thanks again.

**Comment by ilanschnell** [comment]
I'm happy to help!
