### ISSUE TITLE
Feature: Combined bytereverse and make_endian

### ISSUE THREAD

**Issue by kitterma** [ilanschnell/bitarray#203]
I am dealing with a group of datasets which can combine big and little endian binary data.  Currently I'm managing this within bitarray by setting the endianess of the bitarray objects based on the specific data and then checking and reversing the bytes when needed.  When I do this, I need to change both the bit order of the data and the endianness of the resulting bitarray object, which I do in Python in two steps:

> a.bytereverse()
>  b = bitarray.util.make_endian(a, 'little')

Is there an efficiency to gain by doing this in a single function in C?  Maybe that combines the two under the hood, something like:

> b = bitarray.util.byte_endian_reverse(a)

Related, the data isn't always byte aligned, so I have to fill the object to the byte border, do the bytereverse, and then slice out the fill (which is now at the beginning of the last byte) to get back to the correct bit length.

The code I have now works fine, so bitarray does what I need, but if there was a way to make this faster by doing it in a single Python command, that would be useful since I'm somewhat CPU bound at the moment.  If you don't think adding this would be enough faster to be worthwhile, please close the issue and I'll continue looking for other optimizations.

**Comment by ilanschnell** [comment]
You can create a new bitarray with the desired endianness:
```
>>> a = bitarray('101111', 'big')  # create big-endian bitarray
>>> b = bitarray(a, 'little')  # create new bitarray with bits from a, but little-endian
>>> a == b  # the bits are the same
True
>>> a.tobytes() == b.tobytes()  # but their byte representations are reversed
False
>>> a.endian() == b.endian()  # becuase their bit-endianness is opposite
False
```
Does this solve your first problem?  I'm not sure what exactly the second question is.  Can you give an example?

**Comment by kitterma** [comment]
Yes.  It also solves my second one too.  The problem was when you call bytereverse directly on data that's not byte aligned, but this way it just works.  This is related to the documentation issue I brought up in #202.

I'm going to close this as I don't think there's anything new needed.  I'm going to look at the documentation and see if I have any improvements to suggest.  If I do, I'll open a PR with them.  Thanks (for bitarray generally and this specifically).
