### ISSUE TITLE
Installation on WIn 7 under python 2.7 & 3.4 

### ISSUE THREAD

**Issue by P3Hosting** [ilanschnell/bitarray#22]
Running setup.py install results in an error. This happens for both 2.7 & 3.4 versions of python
X:>c:/python34/python.exe setup.py install
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.4
creating build\lib.win-amd64-3.4\bitarray
copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.4\bitarray
copying bitarray__init__.py -> build\lib.win-amd64-3.4\bitarray
running build_ext
building 'bitarray._bitarray' extension
error: Unable to find vcvarsall.bat

**Comment by pbeach6** [comment]
The instructions for installing bitarray should in the readme advise the user if installing on Windows and working with python 2.7 to use the 32 bit version of python 2.7 AND VS C++ 2008 Express.  
The link you have above on stackoverflow claims you can use Python 2.7 64 bit with the SDK installed and that user provides the link to the SDK on stackoverflow... I do not find that this works.
I have seen reports that the 64 bit version can be made to work if you have VS C++ 08 full edition (not express).  
I'm not sure how to get the 64 bit version to work but I feel the readme should have the above info ... at least say use a 32 bit version of python and have express installed...
Took me half a day to find your post and figure this out.

**Comment by techtonik** [comment]
Is it possible to just provide binary wheels for Windows?

**Comment by ilanschnell** [comment]
Anaconda provides binaries conda packages for Windows (and Mac and Linux).
Also on https://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray you can find wheels.

**Comment by ispmarin** [comment]
How can we help to provide a wheel for this package in Windows?

**Comment by jakobkogler** [comment]
@ispmarin There are already wheels for Windows. Have you read the previous answer by ilanschnell?

It would be nice though to publish the precompiled wheels on Pypi.
