### ISSUE TITLE
TypeError: object of type 'bitarray.searchiterator' has no len()

### ISSUE THREAD

**Issue by whu-lyh** [ilanschnell/bitarray#223]
How to call the len() of bitarray? bitarray version is 3.0.0

**Comment by ilanschnell** [comment]
Nothing has changed in version 3.0 to call `len()`:
```
>>> from bitarray import bitarray
>>> a = bitarray('101001100011100)
>>> len(a)
15
```
However, from the title of this issue, I see that you are string to evaluate the length of a searchiterator object.  In version 3.0 the metho `.search()` is now returning no longer a list, but a searchiterator object.  And you cannot call `len()` on the searchiterator object.  However, you can first create a list:
```
>>> len(list(a.search(bitarray('10'))))
4
```
But if call you need is the number of occurrences if a specific sub-bitarray, you can simply use the `.count()` method:
```
>>> a.count(bitarray('10'))
4
```
This will be faster and more memory efficient that creating a list from the searchiterator, only to check it's length.

**Comment by whu-lyh** [comment]
Thanks~
