### ISSUE TITLE
Unhashable

### ISSUE THREAD

**Issue by wreardan** [ilanschnell/bitarray#24]
TypeError: unhashable type: 'bitarray'

It would be useful to be able to use bitarrays as keys in dictionaries, and I don't think implementing this would be too bad, but I'm not familiar with the codebase.

Here's the code that I was trying to use:

```
bitarray_dictionary = {}
reverse_bitarray_dictionary = {}
for i,base in enumerate(dictionary):
    binary = '{0:b}'.format(i)
    b = bitarray(binary)
    bitarray_dictionary[base] = b
    reverse_bitarray_dictionary[b] = base
```

which I could then turn into an iterator:

```
def characters(bitarray):
    for i in range(0, len(bitarray), 2):
        bits = bitarray[i:i+2]
        yield reverse_bitarray_dictionary[bits]

```

Sincerely,
Wesley

**Comment by ambrosejcarr** [comment]
+1

**Comment by akabos** [comment]
My workaround

```
from bitarray import bitarray as _bitarray

class bitarray(_bitarray):
    """ This is required to make bitarray hashable with Py3
        (see http://bit.ly/1NIuA9F for explanation)
    """
    def __hash__(self):
        return id(self)
```

**Comment by karel-brinda** [comment]
If you need to compare independently created bit-arrays, this workaround should work (based on the @akabos's solution):
```python
class bitarray(_bitarray):
    def __hash__(self):
        return self.tobytes().__hash__()
```

**Comment by yoch** [comment]
Mutable objects shouldn't be hashable in general.

**Comment by dargueta** [comment]
This appears to have been changed. Close the ticket?

**Comment by ilanschnell** [comment]
Yes, as @yoch points out, as bitarrays are mutable object, they should not be hashable, which is indeed a bug in Python 2 #74.  I like the solution @karel-brinda suggests!
