### ISSUE TITLE
Feature requests: an immutable type and conversion from/to bytes at offsets

### ISSUE THREAD

**Issue by ceridwen** [ilanschnell/bitarray#25]
1) It would be useful to have an immutable counterpart to the bitarray type, analogous to bytes for bytearray, for hashability and because immutable types are safer in important respects.

2) Struct and similar other built-in functions and methods allow conversion to and from raw binary data at offsets, which is useful for dealing with bit arrays embedded inside larger data structures.

**Comment by ilanschnell** [comment]
That for you requests, and sorry for the late response.

1. As of bitarray 1.1.0, there is an immutable bitarray type called `frozenbitarray`

2. When dealing with large raw binary data files, you can always use the `.seek()` method on the file descriptor and then use bitarrays `.tofile()` or `.fromfile()` methods.  Note that `.fromfile()` allows reading a given number of bytes.  Using `io.BytesIO` you can in fact do the same for in memory data.
