### ISSUE TITLE
Feature: set certain bit(s) to value

### ISSUE THREAD

**Issue by KimiNewt** [ilanschnell/bitarray#27]
Currently you can only append/insert new bits. A useful feature would be to set/toggle certain bits or a bits range, i.e.

bitarr.set(5, True)
bitarr.toggle(5)
bitarr.set_range(5, 10, True)

**Comment by nmichaud** [comment]
This is possible using slicing syntax:

bitarr[5] = True
bitarr[5:10] = True

**Comment by dufferzafar** [comment]
@nmichaud But I don't think it's possible to toggle/flip/invert a particular bit inplace?
