### ISSUE TITLE
Should WITH_BUFFER be defined for python 3?

### ISSUE THREAD

**Issue by isaacl** [ilanschnell/bitarray#32]
I believe it is currently is only set for 2.7:

https://github.com/ilanschnell/bitarray/blob/master/bitarray/_bitarray.c#L51-L54

**Comment by WGH-** [comment]
I've tried to define it on Python 3, but the extension failed to build. I suppose Python 3 has slightly different API for buffer protocol. I'll try to figure it out and submit a pull request.
