### ISSUE TITLE
Check type of length argument

### ISSUE THREAD

**Issue by kallewoof** [ilanschnell/bitarray#34]
I recently passed a float to `bitarray()` without realizing it. It crashed with `"TypeError: could not extend bitarray"` which had me running in circles for a few hours before realizing it. A simple type check in `__init__` may spare others the lost time.

**Comment by ilanschnell** [comment]
I just added a better error message when trying to initialize from float or complex
https://github.com/ilanschnell/bitarray/commit/53b728bda89df9bc6a408615c1c4acd61fe1c933

Will be part of the next release.
