### ISSUE TITLE
Feature Request: efficient way to concatenate lists of bitarrays

### ISSUE THREAD

**Issue by hayne** [ilanschnell/bitarray#38]
In my application, I have thousands of small bitarrays that I need to concatenate to get one large bitarray. There doesn't seem to be an efficient way of doing this.

What I've tried:

```
# Try #1
# Allocate large bitarray, then assign into it at offsets:
numBitArrays = len(bitArrayList)
lengths = [len(bitArray) for bitArray in bitArrayList]
totalNumBits = sum(lengths)
newBitArray = bitarray.bitarray(totalNumBits)
offset = 0
for i in xrange(numBitArrays):
    length = lengths[i]
    newBitArray[offset : offset + length] = bitArrayList[i]
    offset += length

# Try # 2
# Use the + operator to concatenate bitarrays:
newBitArray = bitarray.bitarray(0)
for bitArray in bitArrayList:
    newBitArray += bitArray

# Try #3 
# Get the bits as strings, concatenate strings, then create large bitarray from string
bitsList = list()
for bitArray in bitArrayList:
    bits = bitArray.to01()
    bitsList.append(bits)
newBits = ''.join(bitsList)
newBitArray = bitarray.bitarray(newBits)
```

Surprisingly, the 3rd method seems to be about 25% faster than the others. But it takes more memory and still is a bit slow for my application with 3000 bitarrays to be concatenated

**Comment by diamondman** [comment]
Great request. I have had some similar issues, and was considering forking the project and adding the ability to make a bitarray that has more bits allocated than are used. That way bitarray.extend() would use the available bits instead of always needing to reallocate.

**Comment by ilanschnell** [comment]
@hayne The option 2 you list should be the most efficient.  I'm also surprised that 3 is still faster, I guess the reason is that not so much memory resizing is happening.

Anyway, the following program which appends 10 million small bitarrays only takes 3.3s on my small machine (MacBook Air) to run.  Which means that each 19 bit bitarray only takes about a third micro second to append.
```
a = bitarray()
b = bitarray('0101010010010011110')
for _ in range(10**7):
    a += b
```
