### ISSUE TITLE
Feature Request: cardinality

### ISSUE THREAD

**Issue by remiadon** [ilanschnell/bitarray#41]
Hello everyone,
For one of my projects I would need to get the `cardinality` of a bit array, i.e the number of bits set to 1, [as defined in Java's BitSet class](https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html#cardinality())

For now the simplest way of doing this is using `sum`:
```python
cardinality = sum(1 for i in my_bitarray if i)
```

My issue is that it is no that fast (between 10 and 50ms for a million bits array on my machine), I mean not that fast if I need to compute/use it quite often.

Is there a better way to get the cardinality ?
I suggest the cardinality to be an attribute and incrementing/decrementing it when setting a bit to 1

**Comment by jabbalaci** [comment]
What about `my_bitarray.count()` ?

**Comment by ilanschnell** [comment]
Yes, @jabbalaci!  The `.count()` method does exactly what @remiadon needs.
