### ISSUE TITLE
 Release wheels on Pypi?

### ISSUE THREAD

**Issue by pombredanne** [ilanschnell/bitarray#44]
It would be great to have pre-built wheels on Pypi.
I am vendoring some here:https://github.com/nexB/scancode-toolkit/tree/1ff61e5858186210dd8393f7ee55c20c30168369/thirdparty/prod#cfc12116b3783dcbe14d11617e0230f8-170bd4072ed3b82dc55e8307cacd50d4982cdf8d and I build them with these "build loops" (on Linux, Mac and Windows through Travis and Appveyor):
- https://github.com/pombreda/thirdparty 
- https://github.com/pombreda/thirdparty-manylinux/

I would be willing to help to have this baked in this project.

**Comment by ilanschnell** [comment]
Conda packages are available for all platforms.  Sorry, I'm not planning to make wheels.

**Comment by pombredanne** [comment]
@ilanschnell I can understand this, but do you care if I contribute these and the bits to build the wheels?
