### ISSUE TITLE
"open file expected" on large array

### ISSUE THREAD

**Issue by mjr129** [ilanschnell/bitarray#48]
# Steps to reproduce

```
from bitarray import bitarray
b = bitarray( 114873544900 )
with open( "test.bitarray", "wb" ) as file:
   b.tofile( file )
```

# Observed
* Misleading error message

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: open file expected
```

# Expected
* Save the file successfully
* ...or... a helpful error message

# System details
* OSX Sierra
* Python 3.5

# Assumptions
Given dealing with large data is one of `bitarray`s primary use cases, it should be able to do so.

**Comment by ilanschnell** [comment]
Works for me on Python 2.7 and OSX 10.12.3

**Comment by WuTheFWasThat** [comment]
I just ran into this as well.  I think this might be the error message you get when you run out of disk space

**Comment by mjr129** [comment]
Also fails on Python 3.6.

No disk space issue.
