### ISSUE TITLE
bitarray does not register with collections.Sequence

### ISSUE THREAD

**Issue by egregius313** [ilanschnell/bitarray#49]
Hi, I have been using `bitarray` recently, and I realized that `bitarray` objects are not registered with the `collections.Sequence` abstract base class, even though it implements the necessary `__len__` and `__getattr__`.

This makes code that checks for implementation of the `Container`, `Iterable`, `Sized`, and `Sequence` abstract base classes in the `collections` module fail when using `bitarray`.

**Comment by ilanschnell** [comment]
I believe this has been fixed with the 1.5.0 release which uses Python's sequence methods.
