### ISSUE TITLE
sdist is missing PKG-INFO

### ISSUE THREAD

**Issue by mhbkb** [ilanschnell/bitarray#51]
Hey owners of bitarray,

Looks like the sdist package of bitarray is missing PKG-INFO which will error out when we call `pkginfo.SDist(file_path)`.
`ValueError: No PKG-INFO in archive: ../cache/bitarray-0.8.1.tar.gz`
 https://pypi.python.org/simple/bitarray/

It would be nice if we can include PKG-INFO in sdist at next release. 

Thanks,
Hao

**Comment by ilanschnell** [comment]
The new 0.8.2 release includes this file.
