### ISSUE TITLE
How to save multiple bitarray objects to list

### ISSUE THREAD

**Issue by szhong12** [ilanschnell/bitarray#53]
MemoryError after running the following code:     

bit_list = []
for i in range(3):
    print (i)
    a = bitarray(2**32)
    bit_list.append(a)

**Comment by ilanschnell** [comment]
It is not surpising that you get a MemoryError here.  2^32 bits are 2^29 bytes, which is 500MB.
However, when you try to put this into a list object (which stores each element as a pointer, i.e. 64 bits on a 64 bit architecture) you have 8*(2^32) = 2^35 = 32GB!  That is 64 times more memory intensive!
Does your machine have 32GB of free memory?
