### ISSUE TITLE
ENH: an option to "increment"/iterate a bitarray while keeping the number of set bits constant

### ISSUE THREAD

**Issue by jamasi** [ilanschnell/bitarray#6]
For some tasks it would be useful if bitarray would be able to compute the lexicographically next bit permutation like mentioned on http://www-graphics.stanford.edu/~seander/bithacks.html#NextBitPermutation (at the very bottom). Also some of the other tricks there might be handy as well.

**Comment by ilanschnell** [comment]
Thanks, I've just added `examples/lexico.py` which contains a functions for the next permutation.
