### ISSUE TITLE
Allow set plus resize

### ISSUE THREAD

**Issue by sfreilich** [ilanschnell/bitarray#62]
bitarray's `__setitem__` checks the existing bounds:

```python
>>> b = bitarray.bitarray()
>>> i = 3
>>> b[i] = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: bitarray index out of range
```

For sparser bitarrays, sometimes it's desirable to set an index (or a sequence of indices) to 1, resizing if necessary to accommodate the extra bits.

This can be done with:

```python
>>> b.extend(itertools.repeat(0, i+1-b.length()))
>>> b[i] = True
>>> b
bitarray('0001')
```

But it would be nice if there was a clean an efficient way to do that sort of thing.

**Comment by ilanschnell** [comment]
I intended to `bitarray` object to behave as the Python `list` object.  You get the same `IndexError` when you try to "change" an item in a list:
```
>>> a = []
>>> a[4] = True
IndexError: list assignment index out of range
```
