### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by zaxy78** [ilanschnell/bitarray#63]
Do I have to install this ?

We have many machines on the (Jenkins) CI server. I guess some of them have older version of VS C++...

I case I can't upgrade the CI servers soon, can I skip compilation and download only binaries or something?

**Comment by keelung-yang** [comment]
It's wonderfull if release it by wheel

**Comment by vasily-v-ryabov** [comment]
Voting for wheel based release as well. At least for Windows.

**Comment by vasily-v-ryabov** [comment]
In addition to VC++ build tools bitarray requires Windows SDK for compilation. This is pretty non-trivial for newcomers. While adding .whl package to current release even doesn't require posting new release on PyPI. It could be added to PyPI by twine.

**Comment by hardbyte** [comment]
I agree with the previous comments and am willing to help automate building of cross platform wheels.

I've [forked this repo](https://github.com/hardbyte/bitarray/tree/azure-pipelines) and have setup Azure Devops CI to test and package `bitarray` across linux, mac, and windows. You can see an example build [here](https://dev.azure.com/hardbyte/bitarray/_build/results?buildId=23&view=results).

The Azure Devops project I created is [here](https://dev.azure.com/hardbyte/bitarray/_build?definitionId=1&_a=summary) but I suspect @ilanschnell you would like to create your own (free) account so you can manage permissions and eventually if you're comfortable connect it to pypi for automatic release.

I'll remove the code coverage (as it doesn't include the C extension), and then publishing the wheels to an [azure feed](https://dev.azure.com/hardbyte/bitarray/_packaging?_a=feed&feed=bitarray-preview) so they can be easily installed from pip as a kind of preview.

**Comment by hardbyte** [comment]
Azure feed seems to be working now - https://dev.azure.com/hardbyte/bitarray/_packaging?_a=package&feed=bitarray&package=bitarray&protocolType=PyPI&version=1.0.1

**Comment by keelung-yang** [comment]
There is a great site to download wheels before supporting wheel officially.
https://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray

@hardbyte Urls are broken.

**Comment by hardbyte** [comment]
Sorry my urls changed as I experimented with azure. I'm automatically publishing wheels on pypi as https://pypi.org/project/bitarray-hardbyte/ - my fork is here https://github.com/hardbyte/bitarray

```
pip install bitarray-hardbyte
```

Ideally there are wheels published **officially** upstream.

**Comment by ilanschnell** [comment]
This page has always very up-to-date wheels: https://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray
There's also Anaconda and conda-forge.

**Comment by hardbyte** [comment]
Would you consider adding a note to the readme about the compiler requirement, and perhaps pointing out where/how users can get pre-built binaries?

The link you posted to wheels only has the binaries for Windows. Linux/MacOS users also may not want to have to compile the package just to use it - very nice user experience if `pip install bitarray` just works and is fast.

**Comment by ilanschnell** [comment]
Thanks, I just released 1.5.3 with more install information in the README.

**Comment by filips123** [comment]
@ilanschnell Problem with separate package is that any other package that depends on `bitarray` will most likely fail during installation even though wheels from `bitarray-hardbyte`. Can you merge that PR to automatically build and publish wheels for official package?
