### ISSUE TITLE
Py2 problem: cannot read from a subprocess file, "EOFError: could not find EOF"

### ISSUE THREAD

**Issue by d33tah** [ilanschnell/bitarray#64]
Here's my test case:

```
>>> import bitarray, subprocess
>>> f = subprocess.Popen(['zstd', '-qdc', '20151111-rdns.gz.zstd.coverage.bin.zstd'], stdout=subprocess.PIPE).stdout
>>> b = bitarray.bitarray()
>>> b.fromfile(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EOFError: could not find EOF
```

Only happens under Python2. Not that important since using Py3 is a workaround, but I thought I'd report it anyway.

**Comment by ilanschnell** [comment]
Thanks for reporting the issue.  Bitarray 1.5.0 (which will be released soon) has a unified way of handling file operations across Python 2 and 3.
