### ISSUE TITLE
Add 'top' , 'tail' and 'toint' methods

### ISSUE THREAD

**Issue by NEWME0** [ilanschnell/bitarray#65]
**top(count=1) -> bitarray**
Cut items from begin of array and return them.

\>\>\> from bitarray import bitarray
\>\>\> bitwise = bitarray('00111110')
\>\>\> bitwise.top(2)
bitarray('00')
\>\>\> bitwise
bitarray('111110')

**tail(count=1) -> bitarray**
Cut items from end of array and return them.

\>\>\> from bitarray import bitarray
\>\>\> bitwise = bitarray('00111110')
\>\>\> bitwise.tail(2)
bitarray('10')
\>\>\> bitwise
bitarray('001111')

**Comment by ilanschnell** [comment]
What you want can be easily achieved with standard Python slice syntax already.  For example:
```
>>> a = bitarray('001111110')
>>> a[:2] # top 2
bitarray('00')
>>> a[-2:] # last 2
bitarray('10')
>>> a
bitarray('001111110')
>>> del a[-2:] # remove last 2
>>> a
bitarray('0011111')
```
