### ISSUE TITLE
PyType_Ready usage

### ISSUE THREAD

**Issue by tombo315** [ilanschnell/bitarray#66]
I was evaluating `bitarray` under pypy3 (6.0.0) and was hit with numerous breaks and tracebacks. When escalating my problem to the pypy developers ([issue here](https://bitbucket.org/pypy/pypy/issues/2907/iterator-pyobject-from-extensions-in-pypy3)). The feedback was:

> The issue is this piece of code:
>
> static PyTypeObject DecodeIter_Type = {
> #ifdef IS_PY3K
>     PyVarObject_HEAD_INIT(&DecodeIter_Type, 0)
> #else
>     PyObject_HEAD_INIT(NULL)
>     0,                                        /* ob_size */
> #endif
> ...
> 
> On py3k, it causes the type of object returned by .iterdecode() to be an instance of itself. Additionally, PyType_Ready() is never called, which makes the type invalid, per CPython documentation. This should be fixed in bitarray.

This is consistent with the guidelines for [developing extensions](https://docs.python.org/3/extending/newtypes_tutorial.html?highlight=pytype_ready#defining-extension-types-tutorial).

**Comment by ilanschnell** [comment]
I've added calling `PyType_Ready` a few days ago:
https://github.com/ilanschnell/bitarray/commit/9ec26dcf29b7ab00c4c12ede591a214fec4a0b33

The problematic `DecodeIter_Type` declaration has been fixed a while back.
