### ISSUE TITLE
Iterating set bits is inefficient

### ISSUE THREAD

**Issue by johncrenshaw** [ilanschnell/bitarray#67]
A common need with a bit array is to iterate over all bits that are set (or all bits that are cleared). Right now this is accomplished via `arr.itersearch(bitarray('1'))`, but the internal implementation of `search()` (which is used by `itersearch()`) simply compares bit by bit via two loops. This implementation is ultimately very naive, requiring multiple registers, increments, compares, and jumps for every single bit, regardless of whether the bit is set. This could be sped up dramatically by having a dedicated iterator for set bits. This implementation could walk 32 or 64 bits at a time and quickly skip over regions containing no set bits at potentially hundreds of times the speed of the current implementation (a single QWORD operation replacing 64 masks, compares, bitshifts, increments, and jumps). It is also possible to use a "count trailing zero" and/or "count leading zero" operation to further reduce the number of required bitwise comparisons required in many cases (see https://lemire.me/blog/2018/02/21/iterating-over-set-bits-quickly/).

**Comment by ilanschnell** [comment]
The `.index()` method is slightly better for searching for set bits (when the bitarray is sparse) as it compares whole bytes.  The following function does the same as `a.search(bitarray('1'))`, but is about 3 times faster on large sparse bitarrays.
```
def findsetbits(a):
    res = []
    p = -1
    while 1:
        try:
            p = a.index(1, p + 1)
            res.append(p)
        except ValueError:
            return res
```

**Comment by ilanschnell** [comment]
I've basically added the above code in the C level in ed22c476668d4308b05d52047e5da93c53281f6c
