### ISSUE TITLE
test_bitarray.py: unittest.TestCase.assert_ is deprecated

### ISSUE THREAD

**Issue by chrstphrchvz** [ilanschnell/bitarray#68]
The `unittest.TestCase.assert_()` alias is deprecated in [Python 2.7](https://docs.python.org/2/library/unittest.html#deprecated-aliases) and [Python 3.2+](https://docs.python.org/3/library/unittest.html#deprecated-aliases), so running test_bitarray.py prints 49 warnings like the following:

```
bitarray/test_bitarray.py:65: DeprecationWarning: Please use assertTrue instead.
  self.assert_(0 <= unused < 8)
```

A quick solution might be to use `assertTrue()` instead; however [the unittest library also suggests](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertTrue) using the purpose-specific functions available in Python 2.7/3.1+ (e.g. `assertIs()` and  `assertIsInstance()`).

**Comment by ilanschnell** [comment]
I just pushed 7136bd20295079dee7f08195b02f328df2f38112 to master which removes the deprecated `assert_` methods.  This will be part of the 1.1.0 release.
