### ISSUE TITLE
cannot derive class from bitarray

### ISSUE THREAD

**Issue by goulu** [ilanschnell/bitarray#69]
```
class Sieve(bitarray):
    def __init__(self, init):
        bitarray.__init__(self, init)
        # and more code ...
s=Sieve([False,False,True,True])
```

fails with 
> TypeError: bitarray() argument 2 must be str, not list

(surprisingly when calling Sieve constructor, not the bitarray.__init__ ...)
tried various super() variants, no change...

bitarray 0.8.3 (from Anaconda), python 3.7.1, Windows 10

**Comment by ilanschnell** [comment]
The problem is that you cannot call `bitarray.__init__` with the `self` argument.
When you change the your code to:
```
class Sieve(bitarray):
    def __init__(self, init):
        bitarray.__init__(init)
        # and more code ...
```
Everything should work as expected.
