### ISSUE TITLE
Enhancement: left and right shifting support

### ISSUE THREAD

**Issue by skrossner** [ilanschnell/bitarray#7]
Can you add support for the << and >> operators?   Perhaps look at https://bitbucket.org/quiark/bitarray/src/473cb720d09d/bitarray/_bitarray.c for a reference.  Thanks.

**Comment by Pimmetje** [comment]
+1

**Comment by eli-b** [comment]
+1

**Comment by wmayner** [comment]
+1

**Comment by alexdunn** [comment]
Yes pwease.

**Comment by alexdunn** [comment]
Actually, it looks like one of the outstanding pull requests has this implemented: https://github.com/ilanschnell/bitarray/pull/8

But, it's been open since September 2012.  :sob:

**Comment by rwmanos** [comment]
+1

**Comment by rrrealman** [comment]
Hi guys, is there still need in simple shifts? As I found [here](https://github.com/diamondman/bitarray/pull/9), it was not merged. So, I need this implementation and have time to commit it.

**Comment by adavidzh** [comment]
I just got here because I could not believe that `<<` and `>>` were not implemented. @ilanschnell, any chance you can look into the related PRs?

**Comment by eddydee123** [comment]
@ilanschnell is there any reason not to merge the PR for this feature? Seems like it's an obvious enhancement...

**Comment by ilanschnell** [comment]
I have been thinking about shift operations for a long time, and tried an implementation in a branch.  However, as bitarrays are arrays (and not integers) it seems strange why they should support shift operations.  The Python list object (as well as Python's array library) does not support shift operations either.

**Comment by wmayner** [comment]
IMHO, it depends on the intended scope of the library. If it's meant to be a drop-in replacement for `list`, then perhaps not... but, for example, I would like to use it to deal with the states of dynamical systems with binary-valued elements. Each bit represents the state of a separate element, but when dealing with the phase-space algorithmically it's often convenient & efficient to treat the states as base-2 integers. For that kind of use-case, left and right shift would be useful.

Just my two cents :)

**Comment by ilanschnell** [comment]
Thanks @wmayner for your input.

While it is the list object doesn't support shifts, it also doesn't support `&`, `^`, etc. , while bitarray supports those operations.  While bitarray objects support all list methods, it has many more that are specific to bitarrays.  I have therefore decided that adding support for shift operations is a good idea, and created #117.  I plan to merge #117 before the next release.  Please comment on #117 .  Thanks!
