### ISSUE TITLE
trim zeros

### ISSUE THREAD

**Issue by mabdelaal86** [ilanschnell/bitarray#77]
I have used this library, and it is really awesome.

I just wondering if there is a way to trim zeros from the start and the end of the bitarrray. Just like trimming white spaces from a string in other languages.

thanks a lot,

**Comment by ilanschnell** [comment]
It depends how long the array it, i.e. how critical memory is.
One solution would be:
```
a = bitarray('0010100101001100')
b = bitarray(a.to01().strip('0'))   # bitarray('101001010011')
```

**Comment by ilanschnell** [comment]
If memory is critical, you can first find the location of the first and last `1`, and then slice. 
```
def trim(a):
    "remove zero bits from beginning and end of a given bitarray"
    try:
        first = a.index(1)
    except ValueError:
        return bitarray()
    last = len(a) - 1
    while not a[last]:
        last -= 1
    return a[first:last+1]
```

**Comment by ilanschnell** [comment]
I've added an efficient implementation of this, which will be part of the 1.2.0 release, in the function `bitarray.uitls.strip()`.

**Comment by mabdelaal86** [comment]
Fantastic, that is really great.
Thanks a lot.
