### ISSUE TITLE
ENH: Take advantage of 32-bit instructions

### ISSUE THREAD

**Issue by jrynd** [ilanschnell/bitarray#79]
Most of the code deals with things a bit or a byte at a time. Could some speedup be realized by dealing with chunks of 32 bits when possible?

In particular, doing a misaligned copy would be possible by bitshift operations on a 32-bit buffer, rather than doing everything bitwise.

**Comment by ilanschnell** [comment]
One could even take advantage of 64-bit instructions.  However, I wish to keep the code simple, portable and not add too many special cases.  I recently realized using `memcpy()` (for slice assignment) and `memcmp()` (for comparison) was possible, and I implemented those calls.  The nice thing about these calls is that even tough the bitarray buffer is character (8 bit) based, they will depending on the C library and OS be optimized and portable.
