### ISSUE TITLE
Suggestion: add a resize(n) method

### ISSUE THREAD

**Issue by Lucas-C** [ilanschnell/bitarray#80]
```
If n < size:
    would call delete_n(size - n, n)
Elif n > size:
    would call resize(size + n) and then memset(self->ob_item + old_size , 0x00, n);
```  

If you think this is a good idea, I can submit a PR.

**Comment by ilanschnell** [comment]
What is your motivation behind this idea?  Bitarray objects are already designed to be very conservative with memory, see https://github.com/ilanschnell/bitarray/blob/master/bitarray/_bitarray.c#L128-L136.  As other similar Python objects, such as list and `array.array`, also don't have a resize method.

**Comment by Lucas-C** [comment]
While using a big `bitarray` to build a datastructure close to a sieve of Eratosthenes, I wanted to be able to double its size at some point in my algorithm, without doubling the memory usage of my program, by benefitting from a `realloc`. `resize` does exactly that it seems: https://github.com/ilanschnell/bitarray/blob/master/bitarray/_bitarray.c#L141

Now this is absolutely non critical for my need, and I would totally understand it if you do not want to expose this in your lib Python API. Feel free to close this issue then.

**Comment by ilanschnell** [comment]
Ah, I better understand your usecase now.  A quick way to double the size of a bitarray (without destroying the existing entries, and without creating a new object) would be `a.extend(a)`.  Or you can do something like `a.extend(bitarray(n))`.  These operations are slower than pure resizing, but they should be still quite fast.
