### ISSUE TITLE
2D bitarray 

### ISSUE THREAD

**Issue by vsraptor** [ilanschnell/bitarray#82]
I've created in the past 2D bitarray : 

[bmap2D code](https://github.com/vsraptor/bi/blob/master/lib/bmap2D.py)

[docs](http://www.igrok.site/bmap2D.html)

Of course beign Python lib it will be slower than pure C implementation.

Do you have plans on making NDim interface similar to numpy or this one ?

**Comment by ilanschnell** [comment]
Thanks for suggesting a 2D bitarray.  I have been thinking recently about adding an N dimensional bitarray.  The way I would implement this is by creating thin Python object which translates slices to a single underlying bitarray.

**Comment by vsraptor** [comment]
cool... let me know whenever you have it ... my account is : vsraptor on github

**Comment by pzahemszky** [comment]
I'd be interested in a multi-dimensional bitarray too.
