### ISSUE TITLE
Set bits by idxs ?

### ISSUE THREAD

**Issue by vsraptor** [ilanschnell/bitarray#84]
Is there better/faster way to set bits by list of indexes : 

       def set_by_ixs(val, ixs):
                for i in ixs : val[i] = bitarray("1")

**Comment by ilanschnell** [comment]
In your code `val[i] = bitarray("1")` is actually just doing the same as `val[i] = 1`.  When you assign an element of a bitarray the truth value of the object is used.  That means `val[i] = x` does the same as `val[i] = bool(x)`.  Therefore writing `val[i] = bitarray("1")` is somewhat confusing, and `val[i] = bitarray("0")` would be even more confusing, as `bool(bitarray("0"))` evaluates to `True`.

Back to you original question.  If the indices you want to change in the bitarray can be expressed by a slice operation, you can set them all at once.  For example:
```
a = bitarray(100)
a.setall(0)
a[4:90:3] = 1  # set elements to 1, starting at index 4, with steps of 3 up to index 90
```
This is not different from what you can do with regular Python lists.

In the general case, i.e. you have an iterable with indicies you want to set, you have to basically do what you did:
```
for i in ixs:
    a[i] = 1
```
