### ISSUE TITLE
ba2int() gives different answers for different endianness

### ISSUE THREAD

**Issue by dargueta** [ilanschnell/bitarray#86]
```py
import bitarray as ba
from bitarray.util import ba2int as b2i

b = ba.bitarray("110110110")    # Default is big-endian
print(b[:3])            # Prints: bitarray('110') as expected
assert b2i(b[:3]) == 6  # Works as expected


b = ba.bitarray("110110110", endian="little")
print(b[:3])            # Prints: bitarray('110') as expected
assert b2i(b[:3]) == 6  # Fails -- return value is 3


value = 0
for this_bit in b[:3]:
    value <<= 1
    value |= this_bit

assert value == 6   # Works as expected
```

This is a bit confusing. One can argue that order of the bits is an implementation detail and that, since iterating over a bitarray returns the same order of the bits then converting a bitarray to an integer should give the same results regardless of the array's endianness. If the repr is the same, the operations should (in theory) return the same results, no?

**Comment by ilanschnell** [comment]
The order of the bits (bit endianness) is am implementation detail, just like byte endianness.  Consider:
```
>>> i = 1024
>>> i.to_bytes(2, 'big')
b'\x04\x00'
>>> i.to_bytes(2, 'little')
b'\x00\x04'
```
Note how with different byte order, we get a different representation.  The same is true for bit order:
```
>>> from bitarray.util import int2ba
>>> int2ba(5, 8, 'big')
bitarray('00000101')
>>> int2ba(5, 8, 'little')
bitarray('10100000')
```
One can argue that the `repr` of a bitarray is incomplete, as it does not include the bit endianness.  Does this example help to clarify the problem?

**Comment by dargueta** [comment]
I think my problem was that the `repr` didn't show the endianness but it _does_ make a difference with `ba2int`. Considering the endianness is an argument passed to the constructor, maybe it should show up in the repr as well? Its effects are not completely hidden from the user.
