### ISSUE TITLE
type hinting

### ISSUE THREAD

**Issue by flok99** [ilanschnell/bitarray#88]
Hi,

Please consider adding type hinting.

e.g. https://github.com/flok99/bitarray/commit/f733886b6ac1c7b99059305bf4e6b1177c819757

**Comment by ilanschnell** [comment]
Thanks for the suggestion.  However, the function annotation syntax is incompatible with Python 2.  As I still want to support Python 2, this is not an option.  Python 2 is still widely used, and I'm not planning to drop Python 2 support anytime soon.  Sorry

**Comment by flok99** [comment]
Hi,
I just stumbled on this: [https://www.python.org/dev/peps/pep-0484/#stub-files](url). It looks like one can create a seperate .pyi-file containing the annotations. That way it will stay compatible with py2 as well. Also see [https://github.com/python/typeshed/tree/master/stdlib/2](url) for examples.
