### ISSUE TITLE
best match by overlap 

### ISSUE THREAD

**Issue by vsraptor** [ilanschnell/bitarray#90]
hi I have a python module for doing 2D bitarray ... which I use to do a search by overlap (&) for a clossest match ...
The code is short but use alot of memory. If I do it in a python-loop row-by-row then it is too slow.

Here is the code :

```
  counts = ( self.mem[:upto_row,:] & pat.dup(upto_row+1) ).count_ones(axis='rows')

  ixs = np.argsort(counts)[::-1][:rng] #first-bigger

```
what it does is to duplicate the 'pat'-binary (pat * rows) to match the size of the 2D-array.
Then I do the overlap (&). Finally I count the 1's on every row and pick the the row with the biggest overlap.

The question is : Is there a better way to make if faster and use less memory !? 
  It is OK not to use my 2D module but just bitarray() functionality ? 
  Of course you will have to use row-width as an argument.

year ago I tried Cython for the loop, but didn't have big impact.

**Comment by ilanschnell** [comment]
I wrote a small experimental 2D bitarray class on top of bitarray.  You can find the code here:
https://github.com/ilanschnell/slice-talk/blob/master/2Darray.py
