### ISSUE TITLE
how to do bit operations on lists of bitarrays?

### ISSUE THREAD

**Issue by rf987** [ilanschnell/bitarray#95]
Thanks for the great library.

I know I can peform a bitwise AND by doing:
`(bit_array1&bit_array2)`

How can I calculate the bitwise AND of all bitarrays within a list ?

For example, with the built-in python sets library, I can calculate the intersection of a list of sets by doing:

`set.intersection(*list_of_sets)`

Is there a way to do something like this in bitarray?

I have used the count_and utility method, but it only accepts two bitarrays as input.  
How can I pass a list of many bitarrays into count_and ?

**Comment by ilanschnell** [comment]
The bitwise operators only operate on bitarrays, not lists.  I think what you need is `functools.reduce(bitarray.__and__, lst)` where `lst` is a list of bitarrays.  Here is a small example program which shows how you would use this (I tried this using Python 3.8):
```
import functools
from bitarray import bitarray

lst = [bitarray('010100101011'),
       bitarray('000000111111'),
       bitarray('111110000010')]

result = functools.reduce(bitarray.__and__, lst)

print(result)
```
