### ISSUE TITLE
Pickled arrays: 'bitarray.bitarray' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by piskvorky** [ilanschnell/bitarray#98]
Bloom filters created with [pybloom-live](https://github.com/joseph-fox/python-bloomfilter) use bitarray internally.

Recently, loading these pickled bloom filters started failing with:

```python
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import pickle
>>> x = pickle.load(open('example.pkl', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bitarray.bitarray' object has no attribute '__dict__'
```

We tracked the problem down to `bitarray==1.4.2` (loading works) vs `bitarray==1.5.1` (fails).

Is this pickle incompatibility:
* **expected** (in which cases pybloom-live should maybe update its requirements to `bitarray<1.5.0`)?
* **unexpected** (a bug in bitarray)?

Thanks!

**Comment by ilanschnell** [comment]
I did some major in 1.5.0, and even though there are tests for pickling this issue must have fallen through the cracks.  I'll take a closer look.

**Comment by ilanschnell** [comment]
I can reproduce your error now, but only if I create a pickle file using bitarray 1.4.2 (or below), and then try to load it with bitarray 1.5.0 (or higher).  Within each version of bitarray pickling works fine.  I'm not sure yet what the root cause of this problem is.

**Comment by ilanschnell** [comment]
@piskvorky The reason for this incompatibility is that in 1.5.0 the `bitarray` class is completely implemented in C.  Prior to 1.5.0 the `bitarray` class was defined in Python and would inherit from `_bitarray`.  This also means that the `__dict__` attribute cannot be added.  Pickling machinery somehow knows this and would add an empty dict to the pickle state before 1.5.0, which then fails trying create the object in 1.5.0.  However, when dumping a pickle file with the new version, the empty dict is missing, and everything works as expected.

I don't think it's a good idea to rely on pickle for long term storage of data.  For example, Python 3 uses pickle protocol 4 by default, whereas Python 2 only supports protocols 1, 2 and 3.  I think of pickle as something for short time caching, and if the cache is unreadable (or has been removed) then fine (it's only a cache anyway).

If the compatibility of the pickle data is important (and all your users are on Python 3), when yes: add `bitarray<1.5.0` to the requirements.

**Comment by piskvorky** [comment]
Thanks for the investigation, that explains it. We'll try to migrate the pickles to `bitarray==1.5.1`.

Are there any other such changes planned for near-future bitarray versions?

**Comment by ilanschnell** [comment]
No more such changes are planned for bitarray.

However, I'm not sure what changes to pickle are planned for Python itself.  I haven't touched the pickle code in bitarray in over a decade, but without me even knowing the default pickle protocol in Python 3 is now 4, which is unreadable by Python 2.  I'm not sure what the `.pickle` files are used for in python-bloomfilter, but (like I said earlier) if you want something more persistent, I would probably define a more Python agnostic file format.  For example a binary file with header for the bitarray length, followed by little endian raw binary data (see `.fromfile()` and `'.tofile()`).

Anyway, thanks for using bitarray!

**Comment by piskvorky** [comment]
We're using a fixed Python version, with a fixed pickle version, so that's not an issue. Thanks.

**Comment by ilanschnell** [comment]
I recently added 609c8b9e1cf72937e39445a9f5a153ff9989c989, that is:
  * I created a pickle file using bitarray 1.5.0
  * added the file to the repository
  * created a test for loading this file

So a bug like this won't happen in the future again.
